[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "myhordes-debord"
version = "0.0.1"
dependencies = [
    "click",
]

[project.scripts]
simu = "simu:main"
